import prisma from "@/src/lib/prisma";
import { RoastLevel } from "../../src/app/generated/prisma/client";

export async function seedProducts() {
  await prisma.product.createMany({
    data: [
      {
        name: 'Python Press',
        slug: 'python-press',
        description: 'Indentation so smooth it just flows',
        detailDescription: 'A light roast designed for clarity and balance, Python Press delivers a smooth and elegant cup with subtle citrus notes and a clean finish. Its gentle body and natural sweetness make it perfect for slow mornings or long coding sessions where focus matters more than intensity. Like well-written code, everything just flows.',
        imageUrl: '/assets/images/products/python-press.png',
        price: 10,
        stockQuantity: 30,
        roastLevel: RoastLevel.LIGHT,
        origin: 'Ethiopia',
      },
      {
        name: 'Ruby Roast',
        slug: 'ruby-roast',
        description: 'Optimized for happiness, not just caffeine',
        detailDescription: 'Ruby Roast is a medium roast crafted for comfort and joy. With a rounded body and notes of chocolate and caramel, it offers a balanced cup that feels both indulgent and reliable. Perfect for developers who value elegance and happiness in both their code and their coffee.',
        imageUrl: '/assets/images/products/ruby-roast.png',
        price: 13,
        stockQuantity: 16,
        roastLevel: RoastLevel.MEDIUM,
        origin: 'Colombia',
      },
      {
        name: 'Go Brew',
        slug: 'go-brew',
        description: 'Fast, efficient, no time to sleep',
        detailDescription: 'Built for speed and efficiency, Go Brew is a light roast that delivers a crisp and energizing experience. Bright acidity and subtle fruit notes keep your mind sharp and responsive, making it the ideal companion for fast-paced workflows and early starts.',
        imageUrl: '/assets/images/products/python-press.png',
        price: 11,
        stockQuantity: 28,
        roastLevel: RoastLevel.LIGHT,
        origin: 'Kenya',
      },
      {
        name: 'C Brew',
        slug: 'c-brew',
        description: 'No sugar, no safety, just pure power',
        detailDescription: 'C Brew is a bold dark roast with a strong, uncompromising character. Expect deep roasted flavors, a heavy body, and a powerful finish that hits hard. It’s not for the faint of heart — just like working close to the metal, this coffee demands respect.',
        imageUrl: '/assets/images/products/python-press.png',
        price: 11,
        stockQuantity: 24,
        roastLevel: RoastLevel.DARK,
        origin: 'Brazil',
      },
      {
        name: 'C++ Press',
        slug: 'cpp-press',
        description: 'Twice the caffeine, twice the complexity',
        detailDescription: 'A complex dark roast with layered flavors and a rich, full-bodied profile. C++ Press offers deep cocoa notes with subtle bitterness and a long, intense finish. It rewards those who take the time to understand it — powerful, intricate, and deeply satisfying.',
        imageUrl: '/assets/images/products/python-press.png',
        price: 14,
        stockQuantity: 21,
        roastLevel: RoastLevel.DARK,
        origin: 'Sumatra',
      },
      {
        name: 'C# Shot',
        slug: 'csharp-shot',
        description: 'Sharp, clean, and hits exactly where needed',
        detailDescription: 'C# Shot is a medium roast with a clean, precise flavor profile. Balanced acidity and smooth body make it reliable and consistent, delivering exactly what you need without surprises. A perfect daily driver for focused and structured work.',
        imageUrl: '/assets/images/products/python-press.png',
        price: 13,
        stockQuantity: 20,
        roastLevel: RoastLevel.MEDIUM,
        origin: 'Guatemala',
      },
      {
        name: 'Azure Blend',
        slug: 'azure-blend',
        description: 'Scalable flavor for distributed mornings',
        detailDescription: 'Azure Blend is a medium roast crafted for flexibility and consistency. With smooth chocolate notes and a balanced finish, it adapts to any brewing method or schedule. Whether you’re working locally or across time zones, this coffee scales with you.',
        imageUrl: '/assets/images/products/python-press.png',
        price: 12,
        stockQuantity: 22,
        roastLevel: RoastLevel.MEDIUM,
        origin: 'Colombia',
      },
      {
        name: 'Boolean Brew',
        slug: 'boolean-brew',
        description: 'True energy or false hope — no in-between',
        detailDescription: 'Boolean Brew is a medium roast with a clear and decisive flavor. Smooth body, mild acidity, and a clean finish make every sip predictable and reliable. It’s either exactly what you need — or not — but it will never leave you uncertain.',
        imageUrl: '/assets/images/products/python-press.png',
        price: 10,
        stockQuantity: 26,
        roastLevel: RoastLevel.MEDIUM,
        origin: 'Guatemala',
      },
      {
        name: 'True Roast',
        slug: 'true-roast',
        description: 'Evaluates to true every single morning',
        detailDescription: 'A dark roast that consistently delivers bold flavor and strong energy. True Roast features deep roasted notes, low acidity, and a satisfying finish that never fails. Dependable, powerful, and always correct.',
        imageUrl: '/assets/images/products/python-press.png',
        price: 12,
        stockQuantity: 19,
        roastLevel: RoastLevel.DARK,
        origin: 'Brazil',
      },
      {
        name: 'False Start Decaf',
        slug: 'false-start-decaf',
        description: 'Looks like coffee, crashes on launch',
        detailDescription: 'A light decaf roast that offers the appearance of coffee without the full execution. Smooth and mild with subtle flavor, it’s ideal for late nights or those avoiding caffeine. Just don’t expect a full system startup.',
        imageUrl: '/assets/images/products/python-press.png',
        price: 9,
        stockQuantity: 14,
        roastLevel: RoastLevel.LIGHT,
        origin: 'Mexico',
      },
      {
        name: 'Null Brew Exception',
        slug: 'null-brew-exception',
        description: 'No coffee. No context. No purpose.',
        detailDescription: 'A dark roast that embraces chaos. Intense, bitter, and unpredictable, Null Brew Exception delivers a heavy body with a sharp finish. Not for everyday use — but unforgettable when it happens.',
        imageUrl: '/assets/images/products/python-press.png',
        price: 15,
        stockQuantity: 12,
        roastLevel: RoastLevel.DARK,
        origin: 'Sumatra',
      },
    ],
  })
}