import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html
        lang="en"
        className={`h-full antialiased overflow-x-hidden`}
      >
        <body className="min-h-full flex flex-col">{children}</body>

      </html>
      <footer className="flex justify-center items-center w-screen h-16 mt-10 bg-accent">
      </footer>
    </>
  );
}
