import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Header } from "../components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
        className="h-full antialiased overflow-x-hidden"
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <Header />
          {children}
          <footer />
        </ClerkProvider>
      </body>
     </html>
    )
  }
